#pragma once

#define TK_KB_UNKNOWN           -1
#define TL_KB_SPACE             32
#define TL_KB_APOSTROPHE        39
#define TL_KB_COMMA             44
#define TL_KB_MINUS             45
#define TL_KB_PERIOD            46
#define TL_KB_SLASH             47
#define TL_KB_0                 48
#define TL_KB_1                 49
#define TL_KB_2                 50
#define TL_KB_3                 51
#define TL_KB_4                 52
#define TL_KB_5                 53
#define TL_KB_6                 54
#define TL_KB_7                 55
#define TL_KB_8                 56
#define TL_KB_9                 57
#define TL_KB_SEMICOLON         59
#define TL_KB_EQUAL             61
#define TL_KB_A                 65
#define TL_KB_B                 66
#define TL_KB_C                 67
#define TL_KB_D                 68
#define TL_KB_E                 69
#define TL_KB_F                 70
#define TL_KB_G                 71
#define TL_KB_H                 72
#define TL_KB_I                 73
#define TL_KB_J                 74
#define TL_KB_K                 75
#define TL_KB_L                 76
#define TL_KB_M                 77
#define TL_KB_N                 78
#define TL_KB_O                 79
#define TL_KB_P                 80
#define TL_KB_Q                 81
#define TL_KB_R                 82
#define TL_KB_S                 83
#define TL_KB_T                 84
#define TL_KB_U                 85
#define TL_KB_V                 86
#define TL_KB_W                 87
#define TL_KB_X                 88
#define TL_KB_Y                 89
#define TL_KB_Z                 90
#define TL_KB_LEFT_BRACKET      91
#define TL_KB_BACKSLASH         92
#define TL_KB_RIGHT_BRACKET     93
#define TL_KB_GRAVE_ACCENT      96
#define TL_KB_WORLD_1           161
#define TL_KB_WORLD_2           162
#define TL_KB_ESCAPE            256
#define TL_KB_ENTER             257
#define TL_KB_TAB               258
#define TL_KB_BACKSPACE         259
#define TL_KB_INSERT            260
#define TL_KB_DELETE            261
#define TL_KB_RIGHT             262
#define TL_KB_LEFT              263
#define TL_KB_DOWN              264
#define TL_KB_UP                265
#define TL_KB_PAGE_UP           266
#define TL_KB_PAGE_DOWN         267
#define TL_KB_HOME              268
#define TL_KB_END               269
#define TL_KB_CAPS_LOCK         280
#define TL_KB_SCROLL_LOCK       281
#define TL_KB_NUM_LOCK          282
#define TL_KB_PRINT_SCREEN      283
#define TL_KB_PAUSE             284
#define TL_KB_F1                290
#define TL_KB_F2                291
#define TL_KB_F3                292
#define TL_KB_F4                293
#define TL_KB_F5                294
#define TL_KB_F6                295
#define TL_KB_F7                296
#define TL_KB_F8                297
#define TL_KB_F9                298
#define TL_KB_F10               299
#define TL_KB_F11               300
#define TL_KB_F12               301
#define TL_KB_F13               302
#define TL_KB_F14               303
#define TL_KB_F15               304
#define TL_KB_F16               305
#define TL_KB_F17               306
#define TL_KB_F18               307
#define TL_KB_F19               308
#define TL_KB_F20               309
#define TL_KB_F21               310
#define TL_KB_F22               311
#define TL_KB_F23               312
#define TL_KB_F24               313
#define TL_KB_F25               314
#define TL_KB_KP_0              320
#define TL_KB_KP_1              321
#define TL_KB_KP_2              322
#define TL_KB_KP_3              323
#define TL_KB_KP_4              324
#define TL_KB_KP_5              325
#define TL_KB_KP_6              326
#define TL_KB_KP_7              327
#define TL_KB_KP_8              328
#define TL_KB_KP_9              329
#define TL_KB_KP_DECIMAL        330
#define TL_KB_KP_DIVIDE         331
#define TL_KB_KP_MULTIPLY       332
#define TL_KB_KP_SUBTRACT       333
#define TL_KB_KP_ADD            334
#define TL_KB_KP_ENTER          335
#define TL_KB_KP_EQUAL          336
#define TL_KB_LEFT_SHIFT        340
#define TL_KB_LEFT_CONTROL      341
#define TL_KB_LEFT_ALT          342
#define TL_KB_LEFT_SUPER        343
#define TL_KB_RIGHT_SHIFT       344
#define TL_KB_RIGHT_CONTROL     345
#define TL_KB_RIGHT_ALT         346
#define TL_KB_RIGHT_SUPER       347
#define TL_KB_MENU              348

#define TL_MB_LBUTTON			0
#define TL_MB_RBUTTON			1
#define TL_MB_MBUTTON			2
#define TL_MB_XBUTTON1			3
#define TL_MB_XBUTTON2			4